### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

### navigation ###

nav:
  - RFCs do PHP: index.md
  - Em Fase de Votação:
      - Novos Recursos da ext-dom no PHP 8.4: rfc/novos-recursos-da-ext-dom-no-php-8.4.md
      - Adicionar Métodos de Abertura de Fluxo ao XML{Reader,Writer}: rfc/adicionar-metodos-de-abertura-de-fluxo-ao-xml-reader-e-writer.md
  - Implementadas:
      - PHP 8.4:
          - Analisadores SQL Específicos do Driver PDO: rfc/analisadores-sql-especificos-do-driver-pdo.md
