### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

### navigation ###

nav:
  - RFCs do PHP: index.md
  - Em Fase de Votação:
      - Analisadores SQL específicos do Driver PDO: analisadores-sql-especificos-do-driver-pdo.md
